def decodeintitles(tagtext):
    tagtext = tagtext.replace('Ð ÐµÑÑÐ°Ð¹Ð»Ð¸Ð½Ð³', 'Рестайлинг')
    tagtext = tagtext.replace('Ð£ÐÐ', 'УАЗ')
    tagtext = tagtext.replace('Ð', 'Б')
    tagtext = tagtext.replace('ÐÐ¿ÑÑÐ½ÑÐ¹ Ð¾Ð±ÑÐ°Ð·ÐµÑ', 'Опытный образец')
    tagtext = tagtext.replace('ÐÐ¾Ð½Ð¾ÑÐ½ÑÐ¹ Ð°Ð²ÑÐ¾Ð¼Ð¾Ð±Ð¸Ð»Ñ Ð¤Ð¾ÑÐ¼ÑÐ»Ð°', 'Гоночный автомобиль Формула')
    tagtext = tagtext.replace('ÐÐ¾ÑÐºÐ²Ð¸Ñ', 'Москвич')
    tagtext = tagtext.replace('Ð¡Ð²ÑÑÐ¾Ð³Ð¾Ñ', 'Святогор') 
    tagtext = tagtext.replace('Ð®ÑÐ¸Ð¹ ÐÐ¾Ð»Ð³Ð¾ÑÑÐºÐ¸Ð¹', 'Юрий Долгорукий')
    tagtext = tagtext.replace('ÐÐ½ÑÐ·Ñ ÐÐ»Ð°Ð´Ð¸Ð¼Ð¸Ñ', 'Князь Владимир')
    tagtext = tagtext.replace('ÐÐ­', 'ИЭ')
    tagtext = tagtext.replace('ÐÐÐ', 'ВАЗ')
    tagtext = tagtext.replace('ÐÐºÐ°', 'Ока')
    tagtext = tagtext.replace('Ð¡ÐµÐÐ', 'СеАЗ')
    tagtext = tagtext.replace('ÐÐ°Ð¼ÐÐ', 'КамАЗ')
    tagtext = tagtext.replace('БÐ¾Ð³Ð´Ð°Ð½', 'Богдан')
    tagtext = tagtext.replace('ÐÐ°Ð´ÐµÐ¶Ð´Ð°', 'Надежда')
    tagtext = tagtext.replace('Ð ÑÑÑ', 'Рысь')
    tagtext = tagtext.replace('ÐÐÐ', 'ГАЗ')
	
def decodeindata(tagtext):
    tagtext = tagtext.replace(u'\xa0', '')
    tagtext = tagtext.replace(u'\x80', '')
    tagtext = tagtext.replace(u'\x81', '')
    tagtext = tagtext.replace(u'\x82', '')
    tagtext = tagtext.replace(u'\x83', '')
    tagtext = tagtext.replace(u'\x84', '')
    tagtext = tagtext.replace(u'\x85', '')
    tagtext = tagtext.replace(u'\x87', '')
    tagtext = tagtext.replace(u'\x89', '')
    tagtext = tagtext.replace(u'\x91', '')
    tagtext = tagtext.replace(u'\x93', '')
    tagtext = tagtext.replace(u'\x94', '')
    tagtext = tagtext.replace(u'\â/â', '')
    tagtext = tagtext.replace(u'Ð»â', 'л')
    tagtext = tagtext.replace(u'/â', ' / ')
    tagtext = tagtext.replace(u'ÂÐ».Ñ.â', ' л.с.')
    tagtext = tagtext.replace('ÐÐµÐ½Ð·Ð¸Ð½', 'Бензин')
    tagtext = tagtext.replace('Ð¼Ð¸Ð½Ð¸Ð²Ñ\x8dÐ½', 'Минивэн')
    tagtext = tagtext.replace('Ð¿ÐµÑÐµÐ´Ð½Ð¸Ð¹', 'Передний')
    tagtext = tagtext.replace('ÐÐ¸Ð·ÐµÐ»Ñ\x8c', 'Дизель')
    tagtext = tagtext.replace('Ð°Ð²ÑÐ¾Ð¼Ð°Ñ', 'Автомат')
    tagtext = tagtext.replace('Ð²Ð½ÐµÐ´Ð¾ÑÐ¾Ð¶Ð½Ð¸Ðº 5 Ð´Ð².', 'Внедорожник 5 дв.')
    tagtext = tagtext.replace('Ð¿Ð¾Ð»Ð½Ñ\x8bÐ¹', 'Полный')
    tagtext = tagtext.replace('ÑÑ\x8dÑÑÐ±ÐµÐº 3 Ð´Ð².', 'Хэтчбек 3 дв.')
    tagtext = tagtext.replace('Ð¼ÐµÑÐ°Ð½Ð¸ÐºÐ°', 'Механика')
    tagtext = tagtext.replace('ÑÐ¾Ð±Ð¾Ñ', 'Робот')
    tagtext = tagtext.replace('ÑÐµÐ´Ð°Ð½', 'Седан')
    tagtext = tagtext.replace('ÑÑ\x8dÑÑÐ±ÐµÐº 5 Ð´Ð².', 'Хэтчбек 5 дв.')
    tagtext = tagtext.replace('ÑÐ½Ð¸Ð²ÐµÑÑÐ°Ð» 5 Ð´Ð².', 'Универсал 5 дв.')
    tagtext = tagtext.replace('ÐºÐ¾Ð¼Ð¿Ð°ÐºÑÐ²Ñ\x8dÐ½', 'Компактвэн')
    tagtext = tagtext.replace('Ð»Ð¸ÑÑÐ±ÐµÐº', 'Лифтбек')
    tagtext = tagtext.replace('ÑÐµÑÑ\x8bÐ¹', 'Белый')
    tagtext = tagtext.replace('Ð±ÐµÐ¶ÐµÐ²Ñ\x8bÐ¹', 'Бежевый')
    tagtext = tagtext.replace('ÑÐ¸Ð½Ð¸Ð¹', 'Синий')
    tagtext = tagtext.replace('Ð·Ð°Ð´Ð½Ð¸Ð¹', 'Задний')
    tagtext = tagtext.replace('ÐºÐ°Ð±ÑÐ¸Ð¾Ð»ÐµÑ', 'Кабриолет')
    tagtext = tagtext.replace('â\Ð\xadÐ»ÐµÐºÑÑÐ¾', 'Электро')
    tagtext = tagtext.replace('â\ÐÐ¸Ð±ÑÐ¸Ð´', 'Гибрид')
    tagtext = tagtext.replace('Ð²Ð°ÑÐ¸Ð°ÑÐ¾Ñ', 'Вариатор')
    tagtext = tagtext.replace('Ð¿Ð¸ÐºÐ°Ð¿', 'Пикап')
    tagtext = tagtext.replace('ÐºÐ°Ð±Ð¸Ð½Ð°', 'кабина')
    tagtext = tagtext.replace('Ð´Ð²Ð¾Ð¹Ð½Ð°Ñ\x8f', 'двойная')
    tagtext = tagtext.replace('ÐºÑÐ¿Ðµ', 'Купе')
    tagtext = tagtext.replace('ÑÑÑÐ³Ð¾Ð½', 'Фургон')
    tagtext = tagtext.replace('Ð¿Ð¾Ð»ÑÑÐ¾ÑÐ½Ð°Ñ\x8f', 'полуторная')
	
def decodeinprices(tagtext):
    tagtext = tagtext.replace('Â', '')
    tagtext = tagtext.replace(u'\xa0', '')
    tagtext = tagtext.replace(u'\x82', '')
    tagtext = tagtext.replace('Ð´', '')
    tagtext = tagtext.replace('Ð¾Ñ', '')
    tagtext = tagtext.replace('Ð¾', '')
    tagtext = tagtext.replace('â', '')
    tagtext = tagtext.replace('½', '')
	
def decodeinprobegs(tagtext):
    tagtext1 = tagtext.replace('Â', '')
    tagtext1 = tagtext.replace(u'\xa0', '')
    tagtext1 = tagtext.replace('Ðº', '')
    tagtext1 = tagtext.replace('Ð¼', '')
    tagtext1 = tagtext.replace('Ð\x9dÐ¾Ð²Ñ\x8bÐ¹', 'Новый')
    return tagtext1